contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://yulistic.gitlab.io/"
title         = "Yulistic.com"
canonifyurls  = true
theme         = "Lanyon"

[indexes]
  category  = "categories"
