# hostname (and path) to the root eg. http://spf13.com/
	baseurl = "https://yulistic.github.io/"

# Site title
	title = "Yulistic.com"

# Copyright
#	copyright = "(c) 2016 Jongyul Kim."

# Language
	languageCode = "en-EN"
	hasCJKLanguage= true

# Metadata format
# "yaml", "toml", "json"
	metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
	theme = "hyde-y"

# Pagination
[pagination]
	pagerSize = 10
	path = "page"

# Enable Disqus integration
	disqusShortname = "yulisticgithub"

[permalinks]
	post = "/:year/:month/:title/"
	code = "/:slug/"

[taxonomies]
	tag = "tags"
	topic = "topics"

[author]
	name = "Jongyul Kim"
	email = "yulistic@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
# You can use markdown here.
#brand = "slow<i class='fa fa-star'></i> steady"
	brand = "Slow & Steady"
	topline = "It's just yulistic!"
#footline = "With all my heart <i class='fa fa-heart'></i>"

# Sidebar position
# false, true, "left", "right"
	sidebar = "left"

# Text for the top menu link, which goes the root URL for the site.
# Default (if omitted) is "Home".
	home = "Home"

# Select a syntax highight.
# Check the static/css/highlight directory for options.
	highlight = "default"

# Google Analytics.
	googleAnalytics = "UA-42983013-1"
#gravatarHash = "d2da470451f74ec97d7aa44756087937"

# Sidebar social links.
	github = "yulistic" # Your Github profile ID
	bitbucket = "yulistic" # Your Bitbucket profile ID
	linkedin = "jongyul-kim-a1053013a" # Your LinkedIn profile ID (from public URL)
	googleplus = "" # Your Google+ profile ID
	facebook = "" # Your Facebook profile ID
	twitter = "" # Your Twitter profile ID
	youtube = ""  # Your Youtube channel ID
	flattr = ""  # populate with your flattr uid
	orcid = "0000-0002-6877-0189" # ORCID ID

# Enable raw HTML in markdown (for compatibility)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Ignore raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []
