contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
baseurl       = "https://yulistic.gitlab.io/"
title         = "Yulistic.com"
canonifyurls  = true
theme         = "hyde-x"
hasCJKLanguage= true
disqusShortname = "yulisticgitlab"
MetaDataFormat = "toml"
paginate = 10


[author]
    name = "Jongyul Kim"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
	tag = "tags"

[[menu.main]]
	name = " Posts"
	identifier = "posts"
	url = "/post/"
	pre = "<i class='fa fa-th-list'></i>"
	weight = -110

[[menu.main]]
	name = " Tags"
	url = "/tags/"
	pre = "<i class='fa fa-tags'></i>"
	weight = -109

[[menu.main]]
	name = " Categories"
	url = "/categories/"
	pre = "<i class='fa fa-folder-open'></i>"
	weight = -108

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "It's just yulistic!"
    defaultKeywords = "your,default,page,keywords"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
#theme = "theme-base-08"
	theme = "theme-base-0b"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
	#highlight = "sunburst"
    highlight = "tomorrow-night"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "It's just yulistic!"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "d2da470451f74ec97d7aa44756087937"

    # Sidebar social links, these must be full URLs.
    github = ""
    bitbucket = ""
    stackOverflow = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    flattr = ""  # populate with your flattr uid
